# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-07 22:42
from __future__ import unicode_literals

import calaccess_processed.models.proxies.opencivicdata.base
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0007_auto_20171022_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDFlatBallotMeasureContestProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'ballot measures',
                'indexes': [],
            },
            bases=('elections.ballotmeasurecontest', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDFlatCandidacyProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'candidates',
                'indexes': [],
            },
            bases=('elections.candidacy', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDFlatRetentionContestProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'recall measures',
                'indexes': [],
            },
            bases=('elections.retentioncontest', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
    ]
