# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='interest_rate',
            field=models.CharField(blank=True, help_text='Interest rate of the loan. This is sometimes expressed as a decimal (e.g., 0.10) and other times as a percent (e.g., 10.0% (from LOAN_CD.LOAN_RATE)', max_length=30, verbose_name='interest rate'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='interest_rate',
            field=models.CharField(blank=True, help_text='Interest rate of the loan. This is sometimes expressed as a decimal (e.g., 0.10) and other times as a percent (e.g., 10.0% (from LOAN_CD.LOAN_RATE)', max_length=30, verbose_name='interest rate'),
        ),
    ]
