# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(blank=True, help_text='Election identification number', max_length=3, verbose_name='election identification number')),
                ('election_year', models.IntegerField(db_index=True, help_text='Year of election', verbose_name='year of election')),
                ('election_type', models.CharField(blank=True, help_text='Election type', max_length=100, verbose_name='election type')),
                ('sort_index', models.IntegerField(help_text='The index value is used to preserve sorting of elections,         since multiple elections may occur in a year. A greater sort index         corresponds to a more recent election.', verbose_name='sort index')),
            ],
        ),
    ]
