# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddatafile',
            name='records_count',
            field=models.IntegerField(default=0, help_text='Count of records in the processed file', verbose_name='records count'),
        ),
    ]
