# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0002_auto_20161128_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='intermediary_city',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='intermediary_firstname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='intermediary_lastname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='intermediary_name_suffix',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='intermediary_state',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='intermediary_title',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='intermediary_zip',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_city',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_code',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_committee_id',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_employer',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_firstname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_is_self_employed',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_lastname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_name_suffix',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_occupation',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_state',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_title',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='lender_zip',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='treasurer_city',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='treasurer_firstname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='treasurer_lastname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='treasurer_name_suffix',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='treasurer_state',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='treasurer_title',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2item',
            name='treasurer_zip',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='intermediary_city',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='intermediary_firstname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='intermediary_lastname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='intermediary_name_suffix',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='intermediary_state',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='intermediary_title',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='intermediary_zip',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_city',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_code',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_committee_id',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_employer',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_firstname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_is_self_employed',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_lastname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_name_suffix',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_occupation',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_state',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_title',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='lender_zip',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='treasurer_city',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='treasurer_firstname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='treasurer_lastname',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='treasurer_name_suffix',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='treasurer_state',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='treasurer_title',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversion',
            name='treasurer_zip',
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_city',
            field=models.CharField(blank=True, help_text='City of the guarantor (from LOAN_CD.LOAN_CITY)', max_length=30, verbose_name='guarantor city'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_code',
            field=models.CharField(blank=True, choices=[('COM', 'Committee'), ('IND', 'Individual'), ('OTH', 'Other'), ('PTY', 'Political Party'), ('SCC', 'Small Contributor Committee'), ('???', 'Unknown value')], help_text='Code describing the guarantor (from LOAN_CD.ENTITY_CD)', max_length=3, verbose_name='lender code'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_employer',
            field=models.CharField(blank=True, help_text='Employer of the guarantor (from LOAN_CD.LOAN_EMP)', max_length=200, verbose_name='guarantor employer'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_firstname',
            field=models.CharField(blank=True, help_text='First name of the guarantor (from LOAN_CD.LNDR_NAMF)', max_length=45, verbose_name='guarantor firstname'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_is_self_employed',
            field=models.BooleanField(default=False, help_text='Indicates whether or not the guarantor is self-employed(from LOAN_CD.LOAN_SELF)', verbose_name='guarantor is self employed'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_lastname',
            field=models.CharField(blank=True, help_text='Last name of the guarantor or business name (from LOAN_CD.LNDR_NAML)', max_length=200, verbose_name='guarantor lastname'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_name_suffix',
            field=models.CharField(blank=True, help_text='Name suffix of the guarantor (from LOAN_CD.LNDR_NAMS)', max_length=10, verbose_name='guarantor name suffix'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_occupation',
            field=models.CharField(blank=True, help_text='Occupation of the guarantor (from LOAN_CD.LOAN_OCC)', max_length=60, verbose_name='guarantor occupation'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_state',
            field=models.CharField(blank=True, help_text='State of the guarantor (from LOAN_CD.LOAN_ST)', max_length=2, verbose_name='guarantor state'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_title',
            field=models.CharField(blank=True, help_text='Name title of the guarantor (from LOAN_CD.LNDR_NAMT)', max_length=10, verbose_name='guarantor title'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='guarantor_zip',
            field=models.CharField(blank=True, help_text='Zip code (usually zip5, sometimes zip9) of the guarantor (from LOAN_CD.LOAN_ZIP4)', max_length=10, verbose_name='guarantor zip'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2item',
            name='lender_name',
            field=models.CharField(blank=True, help_text='Name of the lender (from LOAN_CD.INTR_NAML)', max_length=200, verbose_name='lender name'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_city',
            field=models.CharField(blank=True, help_text='City of the guarantor (from LOAN_CD.LOAN_CITY)', max_length=30, verbose_name='guarantor city'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_code',
            field=models.CharField(blank=True, choices=[('COM', 'Committee'), ('IND', 'Individual'), ('OTH', 'Other'), ('PTY', 'Political Party'), ('SCC', 'Small Contributor Committee'), ('???', 'Unknown value')], help_text='Code describing the guarantor (from LOAN_CD.ENTITY_CD)', max_length=3, verbose_name='lender code'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_employer',
            field=models.CharField(blank=True, help_text='Employer of the guarantor (from LOAN_CD.LOAN_EMP)', max_length=200, verbose_name='guarantor employer'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_firstname',
            field=models.CharField(blank=True, help_text='First name of the guarantor (from LOAN_CD.LNDR_NAMF)', max_length=45, verbose_name='guarantor firstname'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_is_self_employed',
            field=models.BooleanField(default=False, help_text='Indicates whether or not the guarantor is self-employed(from LOAN_CD.LOAN_SELF)', verbose_name='guarantor is self employed'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_lastname',
            field=models.CharField(blank=True, help_text='Last name of the guarantor or business name (from LOAN_CD.LNDR_NAML)', max_length=200, verbose_name='guarantor lastname'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_name_suffix',
            field=models.CharField(blank=True, help_text='Name suffix of the guarantor (from LOAN_CD.LNDR_NAMS)', max_length=10, verbose_name='guarantor name suffix'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_occupation',
            field=models.CharField(blank=True, help_text='Occupation of the guarantor (from LOAN_CD.LOAN_OCC)', max_length=60, verbose_name='guarantor occupation'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_state',
            field=models.CharField(blank=True, help_text='State of the guarantor (from LOAN_CD.LOAN_ST)', max_length=2, verbose_name='guarantor state'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_title',
            field=models.CharField(blank=True, help_text='Name title of the guarantor (from LOAN_CD.LNDR_NAMT)', max_length=10, verbose_name='guarantor title'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='guarantor_zip',
            field=models.CharField(blank=True, help_text='Zip code (usually zip5, sometimes zip9) of the guarantor (from LOAN_CD.LOAN_ZIP4)', max_length=10, verbose_name='guarantor zip'),
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversion',
            name='lender_name',
            field=models.CharField(blank=True, help_text='Name of the lender (from LOAN_CD.INTR_NAML)', max_length=200, verbose_name='lender name'),
        ),
        migrations.AlterField(
            model_name='form460scheduleb2item',
            name='loan_date',
            field=models.DateField(help_text='Date of the loan or date the line of credit was established(from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='loan date'),
        ),
        migrations.AlterField(
            model_name='form460scheduleb2itemversion',
            name='loan_date',
            field=models.DateField(help_text='Date of the loan or date the line of credit was established(from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='loan date'),
        ),
    ]
