# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0002_auto_20170320_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncumbentScrapedElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('session', models.IntegerField(verbose_name='session start year')),
                ('date', models.DateField(verbose_name='election date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapedIncumbent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('session', models.IntegerField(verbose_name='session start year')),
                ('category', models.CharField(max_length=100, verbose_name='office category')),
                ('office_name', models.CharField(max_length=100, verbose_name='name of the office')),
                ('name', models.CharField(max_length=200, verbose_name='name of the incumbent')),
                ('scraped_id', models.CharField(max_length=7, verbose_name='scraped identification number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
