# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0003_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(blank=True, help_text='Office name', max_length=100, verbose_name='office name'),
        ),
    ]
