# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0003_incumbentscrapedelection_scrapedincumbent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcandidate',
            name='election',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='calaccess_processed.CandidateScrapedElection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapedproposition',
            name='election',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='calaccess_processed.PropositionScrapedElection'),
            preserve_default=False,
        ),
    ]
