# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0004_auto_20161129_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form460scheduleb1item',
            name='date_incurred',
            field=models.DateField(help_text='Date the loan was made or received (from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='date incurred'),
        ),
        migrations.AlterField(
            model_name='form460scheduleb1itemversion',
            name='date_incurred',
            field=models.DateField(help_text='Date the loan was made or received (from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='date incurred'),
        ),
        migrations.AlterField(
            model_name='form460schedulehitem',
            name='date_incurred',
            field=models.DateField(help_text='Date the loan was made or received (from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='date incurred'),
        ),
        migrations.AlterField(
            model_name='form460schedulehitem',
            name='recipient_occupation',
            field=models.CharField(blank=True, help_text="Occupation of the recipient (from LOAN_CD.LOAN_OCC). Note that, in some cases, the value seems to actually be the recipient's committee ID.", max_length=60, verbose_name='recipient occupation'),
        ),
        migrations.AlterField(
            model_name='form460schedulehitemversion',
            name='date_incurred',
            field=models.DateField(help_text='Date the loan was made or received (from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='date incurred'),
        ),
        migrations.AlterField(
            model_name='form460schedulehitemversion',
            name='recipient_occupation',
            field=models.CharField(blank=True, help_text="Occupation of the recipient (from LOAN_CD.LOAN_OCC). Note that, in some cases, the value seems to actually be the recipient's committee ID.", max_length=60, verbose_name='recipient occupation'),
        ),
    ]
