# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 17:54
from __future__ import unicode_literals

import calaccess_processed.models.proxies.opencivicdata.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20170731_2047'),
        ('calaccess_processed', '0004_ocdcandidacysourceproxy_ocdcandidatecontestpostproxy_ocdcandidatecontestsourceproxy_ocdelectionident'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDBallotMeasureContestIdentifierProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.ballotmeasurecontestidentifier', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDBallotMeasureContestOptionProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.ballotmeasurecontestoption', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDBallotMeasureContestProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.ballotmeasurecontest', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDBallotMeasureContestSourceProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.ballotmeasurecontestsource', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDRetentionContestIdentifierProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.retentioncontestidentifier', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDRetentionContestOptionProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.retentioncontestoption', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDRetentionContestProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.retentioncontest', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
        migrations.CreateModel(
            name='OCDRetentionContestSourceProxy',
            fields=[
            ],
            options={
                # 'indexes': [],
                'proxy': True,
            },
            bases=('elections.retentioncontestsource', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
    ]
