# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0005_auto_20161201_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form460scheduleb2itemold',
            name='amount_paid_or_forgiven',
        ),
        migrations.RemoveField(
            model_name='form460scheduleb2itemversionold',
            name='amount_paid_or_forgiven',
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemold',
            name='amount_repaid_or_forgiven',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid back or forgiven during the period covered by the filing (from LOAN_CD.LOAN_AMT1)', max_digits=14, verbose_name='amount repaid or forgiven'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form460scheduleb2itemversionold',
            name='amount_repaid_or_forgiven',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid back or forgiven during the period covered by the filing (from LOAN_CD.LOAN_AMT1)', max_digits=14, verbose_name='amount repaid or forgiven'),
            preserve_default=False,
        ),
    ]
