# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:47
from __future__ import unicode_literals

import calaccess_processed.models.proxies.opencivicdata.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_maximum_memberships'),
        ('calaccess_processed', '0005_ocdballotmeasurecontestidentifierproxy_ocdballotmeasurecontestoptionproxy_ocdballotmeasurecontestpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDPersonIdentifierProxy',
            fields=[
            ],
            options={
                'proxy': True,
                # 'indexes': [],
            },
            bases=('core.personidentifier', calaccess_processed.models.proxies.opencivicdata.base.OCDProxyModelMixin),
        ),
    ]
