# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0006_auto_20160927_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='election',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='race',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
