# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0006_auto_20161202_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form460scheduleb2itemold',
            old_name='date_paid_or_forgiven',
            new_name='date_repaid_or_forgiven',
        ),
        migrations.RenameField(
            model_name='form460scheduleb2itemversionold',
            old_name='date_paid_or_forgiven',
            new_name='date_repaid_or_forgiven',
        ),
    ]
