# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0007_auto_20160927_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(help_text='Scraped candidate name', max_length=200, verbose_name='candidate name')),
                ('candidate_id', models.CharField(blank=True, help_text='Scraped candidate id', max_length=7, verbose_name='candidate id')),
                ('office_name', models.CharField(blank=True, help_text='Office name', max_length=100, verbose_name='office name')),
                ('office_seat', models.CharField(blank=True, help_text='Office seat number', max_length=3, verbose_name='office seat number')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(blank=True, help_text='Election identification number', max_length=3, verbose_name='election identification number')),
                ('election_year', models.IntegerField(db_index=True, help_text='Year of election', verbose_name='year of election')),
                ('election_type', models.CharField(blank=True, help_text='Election type', max_length=100, verbose_name='election type')),
                ('sort_index', models.IntegerField(help_text='The index value is used to preserve sorting of elections,         since multiple elections may occur in a year. A greater sort index         corresponds to a more recent election.', verbose_name='sort index')),
            ],
        ),
        migrations.AddField(
            model_name='scrapedcandidate',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calaccess_processed.ScrapedElection'),
        ),
    ]
