# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0008_auto_20160927_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition_name', models.CharField(help_text='Scraped proposition name', max_length=200, verbose_name='proposition name')),
                ('description', models.TextField(blank=True, help_text='Scraped proposition description', verbose_name='proposition description')),
                ('scraped_id', models.CharField(help_text='Scraped proposition id', max_length=200, verbose_name='scraped proposition id')),
            ],
        ),
    ]
