# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0008_auto_20161202_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form460ScheduleH2ItemOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.IntegerField(help_text='Line number of the filing form where the loan is itemized (from LOAN_CD.LINE_ITEM)', verbose_name='line item')),
                ('intermediary_title', models.CharField(blank=True, help_text='Name title of the intermediary (from LOAN_CD.INTR_NAMT)', max_length=10, verbose_name='intermediary title')),
                ('intermediary_lastname', models.CharField(blank=True, help_text='Last name of the intermediary or business name (from LOAN_CD.INTR_NAML)', max_length=200, verbose_name='intermediary lastname')),
                ('intermediary_firstname', models.CharField(help_text='First name of the intermediary (from LOAN_CD.INTR_NAMF)', max_length=45, verbose_name='intermediary firstname')),
                ('intermediary_name_suffix', models.CharField(blank=True, help_text='Name suffix of the intermediary (from LOAN_CD.INTR_NAMS)', max_length=10, verbose_name='intermediary name suffix')),
                ('intermediary_city', models.CharField(blank=True, help_text='City of the intermediary (from LOAN_CD.INTR_CITY)', max_length=30, verbose_name='intermediary city')),
                ('intermediary_state', models.CharField(blank=True, help_text='State of the intermediary (from LOAN_CD.INTR_ST)', max_length=2, verbose_name='intermediary state')),
                ('intermediary_zip', models.CharField(blank=True, help_text='Zip code (usually zip5, sometimes zip9) of the intermediary (from LOAN_CD.INTR_ZIP4)', max_length=10, verbose_name='intermediary zip')),
                ('transaction_id', models.CharField(help_text='Identifies a unique transaction across versions of the a given Form 460 filing (from LOAN_CD.TRAN_ID)', max_length=20, verbose_name='transaction id')),
                ('memo_reference_number', models.CharField(blank=True, help_text="A value assigned by the filer which refers to the item'sfootnote in the TEXT_MEMO_CD table (from LOAN_CD.MEMO_REFNO)", max_length=20, verbose_name='memo reference number')),
                ('recipient_code', models.CharField(blank=True, choices=[('COM', 'Committee'), ('IND', 'Individual'), ('OTH', 'Other'), ('PTY', 'Political Party'), ('RCP', 'Recipient committee'), ('SCC', 'Small Contributor Committee'), ('???', 'Unknown value')], help_text='Code describing the recipient (from LOAN_CD.ENTITY_CD)', max_length=3, verbose_name='recipient code')),
                ('recipient_committee_id', models.CharField(blank=True, help_text="recipient's filer identification number, if it is a committee (from LOAN_CD.CMTE_ID)", max_length=9, verbose_name='recipient committee id')),
                ('recipient_title', models.CharField(blank=True, help_text='Name title of the recipient (from LOAN_CD.LNDR_NAMT)', max_length=10, verbose_name='recipient title')),
                ('recipient_lastname', models.CharField(blank=True, help_text='Last name of the recipient or business name (from LOAN_CD.LNDR_NAML)', max_length=200, verbose_name='recipient lastname')),
                ('recipient_firstname', models.CharField(blank=True, help_text='First name of the recipient (from LOAN_CD.LNDR_NAMF)', max_length=45, verbose_name='recipient firstname')),
                ('recipient_name_suffix', models.CharField(blank=True, help_text='Name suffix of the recipient (from LOAN_CD.LNDR_NAMS)', max_length=10, verbose_name='recipient name suffix')),
                ('recipient_city', models.CharField(blank=True, help_text='City of the recipient (from LOAN_CD.LOAN_CITY)', max_length=30, verbose_name='recipient city')),
                ('recipient_state', models.CharField(blank=True, help_text='State of the recipient (from LOAN_CD.LOAN_ST)', max_length=2, verbose_name='recipient state')),
                ('recipient_zip', models.CharField(blank=True, help_text='Zip code (usually zip5, sometimes zip9) of the recipient (from LOAN_CD.LOAN_ZIP4)', max_length=10, verbose_name='recipient zip')),
                ('recipient_employer', models.CharField(blank=True, help_text='Employer of the recipient (from LOAN_CD.LOAN_EMP)', max_length=200, verbose_name='recipient employer')),
                ('recipient_occupation', models.CharField(blank=True, help_text="Occupation of the recipient (from LOAN_CD.LOAN_OCC). Note that, in some cases, the value seems to actually be the recipient's committee ID.", max_length=60, verbose_name='recipient occupation')),
                ('recipient_is_self_employed', models.BooleanField(default=False, help_text='Indicates whether or not the recipient is self-employed(from LOAN_CD.LOAN_SELF)', verbose_name='recipient is self employed')),
                ('treasurer_title', models.CharField(blank=True, help_text="Name title of the recipient committee's treasurer (from LOAN_CD.TRES_NAMT)", max_length=10, verbose_name='treasurer title')),
                ('treasurer_lastname', models.CharField(blank=True, help_text="Last name of the recipient committee's treasurer (from LOAN_CD.TRES_NAML)", max_length=200, verbose_name='treasurer lastname')),
                ('treasurer_firstname', models.CharField(help_text="First name of the recipient committee's treasurer (from LOAN_CD.TRES_NAMF)", max_length=45, verbose_name='treasurer firstname')),
                ('treasurer_name_suffix', models.CharField(blank=True, help_text="Name suffix of the recipient committee's treasurer (from LOAN_CD.TRES_NAMS)", max_length=10, verbose_name='treasurer name suffix')),
                ('treasurer_city', models.CharField(blank=True, help_text="City of the recipient committee's treasurer (from LOAN_CD.TRES_CITY)", max_length=30, verbose_name='treasurer city')),
                ('treasurer_state', models.CharField(blank=True, help_text="State of the recipient committee's treasurer (from LOAN_CD.TRES_ST)", max_length=2, verbose_name='treasurer state')),
                ('treasurer_zip', models.CharField(blank=True, help_text="Zip code (usually zip5, sometimes zip9) of the recipient committee's treasurer (from LOAN_CD.TRES_ZIP4)", max_length=10, verbose_name='treasurer zip')),
                ('date_repaid_or_forgiven', models.DateField(help_text='Date when the loan repayment or forgiveness occurred (from LOAN_CD.LOAN_DATE2)', null=True, verbose_name='date paid or forgiven')),
                ('date_of_original_loan', models.DateField(help_text='Date the loan was orginally made (from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='date of original loan')),
                ('interest_rate', models.CharField(blank=True, help_text='Interest rate of the loan. This is sometimes expressed as a decimal (e.g., 0.10) and other times as a percent (e.g., 10.0% (from LOAN_CD.LOAN_RATE)', max_length=30, verbose_name='interest rate')),
                ('repayment_type', models.CharField(choices=[('H2F', 'Forgiven'), ('H2R', 'Repay'), ('H2T', 'Third party payment')], help_text='Indicates whether the item is a loan repayment to the campaign filer, a repayment by a third-party or a loan forgiveness by the campaign filer (from LOAN_CD.LOAN_TYPE)', max_length=3, verbose_name='repayment type')),
                ('amount_repaid_or_forgiven', models.DecimalField(decimal_places=2, help_text='Amount paid back or forgiven during the period covered by the filing (from LOAN_CD.LOAN_AMT1)', max_digits=14, verbose_name='amount repaid or forgiven')),
                ('outstanding_principle', models.DecimalField(decimal_places=2, help_text='Outstanding balance of the loan at the end of the period covered by the filing (from LOAN_CD.LOAN_AMT2)', max_digits=14, verbose_name='outstanding principle')),
                ('filing', models.ForeignKey(help_text='Foreign key referring to the Form 460 on which the loan was reported (from LOAN_CD.FILING_ID)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_h2_items_old', to='calaccess_processed.Form460Filing')),
            ],
        ),
        migrations.CreateModel(
            name='Form460ScheduleH2ItemVersionOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.IntegerField(help_text='Line number of the filing form where the loan is itemized (from LOAN_CD.LINE_ITEM)', verbose_name='line item')),
                ('intermediary_title', models.CharField(blank=True, help_text='Name title of the intermediary (from LOAN_CD.INTR_NAMT)', max_length=10, verbose_name='intermediary title')),
                ('intermediary_lastname', models.CharField(blank=True, help_text='Last name of the intermediary or business name (from LOAN_CD.INTR_NAML)', max_length=200, verbose_name='intermediary lastname')),
                ('intermediary_firstname', models.CharField(help_text='First name of the intermediary (from LOAN_CD.INTR_NAMF)', max_length=45, verbose_name='intermediary firstname')),
                ('intermediary_name_suffix', models.CharField(blank=True, help_text='Name suffix of the intermediary (from LOAN_CD.INTR_NAMS)', max_length=10, verbose_name='intermediary name suffix')),
                ('intermediary_city', models.CharField(blank=True, help_text='City of the intermediary (from LOAN_CD.INTR_CITY)', max_length=30, verbose_name='intermediary city')),
                ('intermediary_state', models.CharField(blank=True, help_text='State of the intermediary (from LOAN_CD.INTR_ST)', max_length=2, verbose_name='intermediary state')),
                ('intermediary_zip', models.CharField(blank=True, help_text='Zip code (usually zip5, sometimes zip9) of the intermediary (from LOAN_CD.INTR_ZIP4)', max_length=10, verbose_name='intermediary zip')),
                ('transaction_id', models.CharField(help_text='Identifies a unique transaction across versions of the a given Form 460 filing (from LOAN_CD.TRAN_ID)', max_length=20, verbose_name='transaction id')),
                ('memo_reference_number', models.CharField(blank=True, help_text="A value assigned by the filer which refers to the item'sfootnote in the TEXT_MEMO_CD table (from LOAN_CD.MEMO_REFNO)", max_length=20, verbose_name='memo reference number')),
                ('recipient_code', models.CharField(blank=True, choices=[('COM', 'Committee'), ('IND', 'Individual'), ('OTH', 'Other'), ('PTY', 'Political Party'), ('RCP', 'Recipient committee'), ('SCC', 'Small Contributor Committee'), ('???', 'Unknown value')], help_text='Code describing the recipient (from LOAN_CD.ENTITY_CD)', max_length=3, verbose_name='recipient code')),
                ('recipient_committee_id', models.CharField(blank=True, help_text="recipient's filer identification number, if it is a committee (from LOAN_CD.CMTE_ID)", max_length=9, verbose_name='recipient committee id')),
                ('recipient_title', models.CharField(blank=True, help_text='Name title of the recipient (from LOAN_CD.LNDR_NAMT)', max_length=10, verbose_name='recipient title')),
                ('recipient_lastname', models.CharField(blank=True, help_text='Last name of the recipient or business name (from LOAN_CD.LNDR_NAML)', max_length=200, verbose_name='recipient lastname')),
                ('recipient_firstname', models.CharField(blank=True, help_text='First name of the recipient (from LOAN_CD.LNDR_NAMF)', max_length=45, verbose_name='recipient firstname')),
                ('recipient_name_suffix', models.CharField(blank=True, help_text='Name suffix of the recipient (from LOAN_CD.LNDR_NAMS)', max_length=10, verbose_name='recipient name suffix')),
                ('recipient_city', models.CharField(blank=True, help_text='City of the recipient (from LOAN_CD.LOAN_CITY)', max_length=30, verbose_name='recipient city')),
                ('recipient_state', models.CharField(blank=True, help_text='State of the recipient (from LOAN_CD.LOAN_ST)', max_length=2, verbose_name='recipient state')),
                ('recipient_zip', models.CharField(blank=True, help_text='Zip code (usually zip5, sometimes zip9) of the recipient (from LOAN_CD.LOAN_ZIP4)', max_length=10, verbose_name='recipient zip')),
                ('recipient_employer', models.CharField(blank=True, help_text='Employer of the recipient (from LOAN_CD.LOAN_EMP)', max_length=200, verbose_name='recipient employer')),
                ('recipient_occupation', models.CharField(blank=True, help_text="Occupation of the recipient (from LOAN_CD.LOAN_OCC). Note that, in some cases, the value seems to actually be the recipient's committee ID.", max_length=60, verbose_name='recipient occupation')),
                ('recipient_is_self_employed', models.BooleanField(default=False, help_text='Indicates whether or not the recipient is self-employed(from LOAN_CD.LOAN_SELF)', verbose_name='recipient is self employed')),
                ('treasurer_title', models.CharField(blank=True, help_text="Name title of the recipient committee's treasurer (from LOAN_CD.TRES_NAMT)", max_length=10, verbose_name='treasurer title')),
                ('treasurer_lastname', models.CharField(blank=True, help_text="Last name of the recipient committee's treasurer (from LOAN_CD.TRES_NAML)", max_length=200, verbose_name='treasurer lastname')),
                ('treasurer_firstname', models.CharField(help_text="First name of the recipient committee's treasurer (from LOAN_CD.TRES_NAMF)", max_length=45, verbose_name='treasurer firstname')),
                ('treasurer_name_suffix', models.CharField(blank=True, help_text="Name suffix of the recipient committee's treasurer (from LOAN_CD.TRES_NAMS)", max_length=10, verbose_name='treasurer name suffix')),
                ('treasurer_city', models.CharField(blank=True, help_text="City of the recipient committee's treasurer (from LOAN_CD.TRES_CITY)", max_length=30, verbose_name='treasurer city')),
                ('treasurer_state', models.CharField(blank=True, help_text="State of the recipient committee's treasurer (from LOAN_CD.TRES_ST)", max_length=2, verbose_name='treasurer state')),
                ('treasurer_zip', models.CharField(blank=True, help_text="Zip code (usually zip5, sometimes zip9) of the recipient committee's treasurer (from LOAN_CD.TRES_ZIP4)", max_length=10, verbose_name='treasurer zip')),
                ('date_repaid_or_forgiven', models.DateField(help_text='Date when the loan repayment or forgiveness occurred (from LOAN_CD.LOAN_DATE2)', null=True, verbose_name='date paid or forgiven')),
                ('date_of_original_loan', models.DateField(help_text='Date the loan was orginally made (from LOAN_CD.LOAN_DATE1)', null=True, verbose_name='date of original loan')),
                ('interest_rate', models.CharField(blank=True, help_text='Interest rate of the loan. This is sometimes expressed as a decimal (e.g., 0.10) and other times as a percent (e.g., 10.0% (from LOAN_CD.LOAN_RATE)', max_length=30, verbose_name='interest rate')),
                ('repayment_type', models.CharField(choices=[('H2F', 'Forgiven'), ('H2R', 'Repay'), ('H2T', 'Third party payment')], help_text='Indicates whether the item is a loan repayment to the campaign filer, a repayment by a third-party or a loan forgiveness by the campaign filer (from LOAN_CD.LOAN_TYPE)', max_length=3, verbose_name='repayment type')),
                ('amount_repaid_or_forgiven', models.DecimalField(decimal_places=2, help_text='Amount paid back or forgiven during the period covered by the filing (from LOAN_CD.LOAN_AMT1)', max_digits=14, verbose_name='amount repaid or forgiven')),
                ('outstanding_principle', models.DecimalField(decimal_places=2, help_text='Outstanding balance of the loan at the end of the period covered by the filing (from LOAN_CD.LOAN_AMT2)', max_digits=14, verbose_name='outstanding principle')),
                ('filing_version', models.ForeignKey(help_text='Foreign key referring to the version of the Form 460 that includes the outstanding loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_h2_items_old', to='calaccess_processed.Form460FilingVersion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='form460scheduleh2itemversionold',
            unique_together=set([('filing_version', 'line_item')]),
        ),
        migrations.AlterIndexTogether(
            name='form460scheduleh2itemversionold',
            index_together=set([('filing_version', 'line_item')]),
        ),
        migrations.AlterUniqueTogether(
            name='form460scheduleh2itemold',
            unique_together=set([('filing', 'line_item')]),
        ),
    ]
