# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0008_auto_20170924_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocdflatballotmeasurecontestproxy',
            options={'verbose_name_plural': 'ballot measures'},
        ),
        migrations.AlterModelOptions(
            name='ocdflatcandidacyproxy',
            options={'verbose_name_plural': 'candidates'},
        ),
        migrations.AlterModelOptions(
            name='ocdflatretentioncontestproxy',
            options={'verbose_name_plural': 'recall measures'},
        ),
    ]
