# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 15:04
from __future__ import unicode_literals

import calaccess_processed
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0009_auto_20171003_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDataVersionZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_archive', models.FileField(help_text='An archive zip of processed files', max_length=255, upload_to=calaccess_processed.archive_directory_path, verbose_name='cleaned files zip archive')),
                ('zip_size', models.BigIntegerField(default=0, help_text='The expected size (in bytes) of the zip of processed files', verbose_name='zip of size (in bytes)')),
                ('version', models.ForeignKey(help_text='Foreign key referencing the processed version of CAL-ACCESS', on_delete=django.db.models.deletion.CASCADE, related_name='zips', to='calaccess_processed.ProcessedDataVersion', verbose_name='processed data version')),
            ],
            options={
                'ordering': ('-version', 'zip_archive'),
                'verbose_name': 'TRACKING: CAL-ACCESS processed data version zip',
            },
        ),
    ]
