# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0009_auto_20161202_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form460scheduleb2itemold',
            options={'verbose_name_plural': 'Form460 schedule b2 items old'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleb2itemversionold',
            options={'verbose_name_plural': 'Form460 schedule b2 item versions old'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleh2itemold',
            options={'verbose_name_plural': 'Form460 schedule h2 items old'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleh2itemversionold',
            options={'verbose_name_plural': 'Form460 schedule h2 item versions old'},
        ),
    ]
