# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0009_scrapedproposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedproposition',
            name='proposition_name',
        ),
        migrations.AddField(
            model_name='scrapedproposition',
            name='proposition_number',
            field=models.IntegerField(default=1, help_text='Scraped proposition number', verbose_name='proposition number'),
            preserve_default=False,
        ),
    ]
