# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0005_auto_20161130_0044'),
        ('calaccess_processed', '0010_auto_20161202_1642'),
    ]

    operations = [
    ]
