# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0010_auto_20160928_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedelection',
            name='election_date',
            field=models.DateField(help_text='Date of election', null=True, verbose_name='date of election'),
        ),
        migrations.AddField(
            model_name='scrapedproposition',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calaccess_processed.ScrapedElection'),
        ),
        migrations.AlterField(
            model_name='scrapedproposition',
            name='scraped_id',
            field=models.CharField(help_text='Scraped proposition id', max_length=200, verbose_name='proposition id'),
        ),
    ]
