# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0011_auto_20160928_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_name', models.CharField(help_text='Scraped committee name', max_length=200, verbose_name='committee name')),
                ('scraped_id', models.CharField(help_text='Scraped committee id', max_length=200, verbose_name='committee id')),
                ('support', models.BooleanField(help_text='Whether the committee supports the proposition', verbose_name='supports proposition')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calaccess_processed.ScrapedProposition')),
            ],
        ),
    ]
