# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0011_merge_20161205_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('P', 'Primary'), ('G', 'General'), ('S', 'Special'), ('R', 'Recall')], help_text='Type of election', max_length=1, verbose_name='election type'),
        ),
        migrations.AlterField(
            model_name='election',
            name='year',
            field=models.CharField(help_text='Election year', max_length=4, verbose_name='election year'),
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together=set([('election_type', 'year')]),
        ),
        migrations.AlterIndexTogether(
            name='election',
            index_together=set([('election_type', 'year')]),
        ),
    ]
