# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0011_auto_20171023_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawFilerToFilerTypeCdProxy',
        ),
        migrations.DeleteModel(
            name='ScrapedCandidateElectionProxy',
        ),
        migrations.DeleteModel(
            name='ScrapedCandidateProxy',
        ),
        migrations.DeleteModel(
            name='ScrapedIncumbentElectionProxy',
        ),
        migrations.DeleteModel(
            name='ScrapedIncumbentProxy',
        ),
        migrations.DeleteModel(
            name='ScrapedPropositionElectionProxy',
        ),
        migrations.DeleteModel(
            name='ScrapedPropositionProxy',
        ),
        migrations.AlterField(
            model_name='form460scheduleaitem',
            name='transaction_type',
            field=models.CharField(choices=[('F', 'Forgiven Loan'), ('I', 'Intermediary'), ('R', 'Returned (Negative Amount?)'), ('T', 'Third Party Repayment'), ('X', 'Transfer'), ('', 'Unknown'), ('INC16168', 'Unknown')], help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=255, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460scheduleaitemversion',
            name='transaction_type',
            field=models.CharField(choices=[('F', 'Forgiven Loan'), ('I', 'Intermediary'), ('R', 'Returned (Negative Amount?)'), ('T', 'Third Party Repayment'), ('X', 'Transfer'), ('', 'Unknown'), ('INC16168', 'Unknown')], help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=255, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460schedulecitem',
            name='transaction_type',
            field=models.CharField(choices=[('F', 'Forgiven Loan'), ('I', 'Intermediary'), ('R', 'Returned (Negative Amount?)'), ('T', 'Third Party Repayment'), ('X', 'Transfer'), ('', 'Unknown'), ('INC16168', 'Unknown')], help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=255, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460schedulecitemversion',
            name='transaction_type',
            field=models.CharField(choices=[('F', 'Forgiven Loan'), ('I', 'Intermediary'), ('R', 'Returned (Negative Amount?)'), ('T', 'Third Party Repayment'), ('X', 'Transfer'), ('', 'Unknown'), ('INC16168', 'Unknown')], help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=255, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460scheduleiitem',
            name='transaction_type',
            field=models.CharField(choices=[('F', 'Forgiven Loan'), ('I', 'Intermediary'), ('R', 'Returned (Negative Amount?)'), ('T', 'Third Party Repayment'), ('X', 'Transfer'), ('', 'Unknown'), ('INC16168', 'Unknown')], help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=255, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460scheduleiitemversion',
            name='transaction_type',
            field=models.CharField(choices=[('F', 'Forgiven Loan'), ('I', 'Intermediary'), ('R', 'Returned (Negative Amount?)'), ('T', 'Third Party Repayment'), ('X', 'Transfer'), ('', 'Unknown'), ('INC16168', 'Unknown')], help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=255, verbose_name='transaction type'),
        ),
    ]
