# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0012_scrapedcommittee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedproposition',
            name='proposition_number',
        ),
        migrations.AddField(
            model_name='scrapedproposition',
            name='name',
            field=models.CharField(default='Hi', help_text='Scraped proposition name', max_length=200, verbose_name='proposition name'),
            preserve_default=False,
        ),
    ]
