# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0012_auto_20171110_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form460scheduleaitem',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=50, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460scheduleaitemversion',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=50, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460schedulecitem',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=50, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460schedulecitemversion',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=50, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460scheduleiitem',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=50, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='form460scheduleiitemversion',
            name='transaction_type',
            field=models.CharField(help_text='Type of transaction (from RCPT_CD.TRAN_TYPE)', max_length=50, verbose_name='transaction type'),
        ),
    ]
