# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0012_auto_20161213_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='district',
            field=models.IntegerField(help_text='If a special election, district for the office sought (if applicable)', null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='election',
            name='election_date',
            field=models.DateField(help_text='Date of the election', null=True, verbose_name='election date'),
        ),
        migrations.AddField(
            model_name='election',
            name='office',
            field=models.CharField(choices=[('ASM', 'State Assembly'), ('GOV', 'Governor'), ('SEN', 'State Senate')], help_text='If a special election, office sought', max_length=3, null=True, verbose_name='office'),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('P', 'Primary'), ('G', 'General'), ('R', 'Recall'), ('SE', 'Special Election'), ('SR', 'Special Runoff')], help_text='Type of election', max_length=2, verbose_name='election type'),
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='election',
            index_together=set([]),
        ),
    ]
