# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 21:20
from __future__ import unicode_literals

import calaccess_processed.models.proxies.calaccess_scraped.base
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_raw', '0015_auto_20170729_0218'),
        ('calaccess_scraped', '0002_auto_20170628_1500'),
        ('calaccess_processed', '0013_auto_20180319_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFilerToFilerTypeCdProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('calaccess_raw.filertofilertypecd',),
        ),
        migrations.CreateModel(
            name='ScrapedCandidateElectionProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=(calaccess_processed.models.proxies.calaccess_scraped.base.ElectionProxyMixin, 'calaccess_scraped.candidateelection'),
        ),
        migrations.CreateModel(
            name='ScrapedCandidateProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('calaccess_scraped.candidate', calaccess_processed.models.proxies.calaccess_scraped.base.ScrapedNameMixin),
        ),
        migrations.CreateModel(
            name='ScrapedIncumbentElectionProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=(calaccess_processed.models.proxies.calaccess_scraped.base.ElectionProxyMixin, 'calaccess_scraped.incumbentelection'),
        ),
        migrations.CreateModel(
            name='ScrapedIncumbentProxy',
            fields=[
            ],
            options={
                'ordering': ['-session'],
                'indexes': [],
                'proxy': True,
            },
            bases=('calaccess_scraped.incumbent', calaccess_processed.models.proxies.calaccess_scraped.base.ScrapedNameMixin),
        ),
        migrations.CreateModel(
            name='ScrapedPropositionElectionProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=(calaccess_processed.models.proxies.calaccess_scraped.base.ElectionProxyMixin, 'calaccess_scraped.propositionelection'),
        ),
        migrations.CreateModel(
            name='ScrapedPropositionProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('calaccess_scraped.proposition',),
            managers=[
                ('ballot_measures', django.db.models.manager.Manager()),
            ],
        ),
    ]
