# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0013_auto_20160928_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcommittee',
            name='scraped_id',
            field=models.CharField(help_text='Scraped committee id', max_length=7, verbose_name='committee id'),
        ),
        migrations.AlterField(
            model_name='scrapedcommittee',
            name='scraped_name',
            field=models.CharField(help_text='Scraped committee name', max_length=500, verbose_name='committee name'),
        ),
    ]
