# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0014_pgcrypto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilerIDValue',
        ),
        migrations.DeleteModel(
            name='FilingIDValue',
        ),
    ]
