# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0014_auto_20161216_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='election',
        ),
        migrations.RemoveField(
            model_name='propositioncommittee',
            name='propositions',
        ),
        migrations.RemoveField(
            model_name='propositionsupportoppose',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='propositionsupportoppose',
            name='proposition',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='Proposition',
        ),
        migrations.DeleteModel(
            name='PropositionCommittee',
        ),
        migrations.DeleteModel(
            name='PropositionSupportOppose',
        ),
    ]
