# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0014_auto_20160928_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedcandidate',
            old_name='candidate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scrapedcandidate',
            old_name='candidate_id',
            new_name='scraped_id',
        ),
        migrations.RenameField(
            model_name='scrapedcommittee',
            old_name='scraped_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scrapedelection',
            old_name='election_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='scrapedelection',
            old_name='election_year',
            new_name='year',
        ),
    ]
