# Generated by Django 4.0.7 on 2022-09-10 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calaccess_processed", "0016_auto_20210619_1139"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessedDataFile",
        ),
        migrations.DeleteModel(
            name="ProcessedDataVersion",
        ),
        migrations.DeleteModel(
            name="ProcessedDataZip",
        ),
    ]
