# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0016_auto_20170119_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='administrative_org_id',
            new_name='administrative_org',
        ),
    ]
