# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0017_remove_scrapedcandidate_office_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedcommittee',
            name='support',
        ),
        migrations.AddField(
            model_name='scrapedcandidate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedcandidate',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrapedcommittee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedcommittee',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrapedcommittee',
            name='position',
            field=models.CharField(default='SUPPORT', help_text='Whether the committee supports or opposes the proposition', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedelection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedelection',
            name='date',
            field=models.DateField(null=True, verbose_name='date of election'),
        ),
        migrations.AddField(
            model_name='scrapedelection',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrapedelection',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapedproposition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedproposition',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scrapedcandidate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapedcandidate',
            name='office_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapedcandidate',
            name='scraped_id',
            field=models.CharField(blank=True, max_length=7, verbose_name='candidate identification number'),
        ),
        migrations.AlterField(
            model_name='scrapedcommittee',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scrapedcommittee',
            name='scraped_id',
            field=models.CharField(max_length=7, verbose_name='committee identification number'),
        ),
        migrations.AlterField(
            model_name='scrapedelection',
            name='election_id',
            field=models.CharField(blank=True, max_length=3, verbose_name='election identification number'),
        ),
        migrations.AlterField(
            model_name='scrapedelection',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapedelection',
            name='sort_index',
            field=models.IntegerField(help_text='The index value is used to preserve sorting of elections, since multiple elections may occur in a year. A greater sort index corresponds to a more recent election.', null=True),
        ),
        migrations.AlterField(
            model_name='scrapedelection',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='year of election'),
        ),
        migrations.AlterField(
            model_name='scrapedproposition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapedproposition',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapedproposition',
            name='scraped_id',
            field=models.CharField(max_length=200, verbose_name='proposition identification number'),
        ),
    ]
