# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0018_auto_20161018_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScrapedElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('election_id', models.CharField(blank=True, max_length=3, verbose_name='election identification number')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('sort_index', models.IntegerField(help_text='The index value is used to preserve sorting of elections, since multiple elections may occur in a year. A greater sort index corresponds to a more recent election.', null=True)),
                ('year', models.IntegerField(db_index=True, verbose_name='year of election')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropositionScrapedElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('election_id', models.CharField(blank=True, max_length=3, verbose_name='election identification number')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('sort_index', models.IntegerField(help_text='The index value is used to preserve sorting of elections, since multiple elections may occur in a year. A greater sort index corresponds to a more recent election.', null=True)),
                ('date', models.DateField(null=True, verbose_name='date of election')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='scrapedcandidate',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calaccess_processed.CandidateScrapedElection'),
        ),
        migrations.AlterField(
            model_name='scrapedproposition',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calaccess_processed.PropositionScrapedElection'),
        ),
        migrations.DeleteModel(
            name='ScrapedElection',
        ),
    ]
