# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0018_auto_20170123_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=300)),
                ('scheme', models.CharField(max_length=300)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='calaccess_processed.Election')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
