# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0019_electionidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='abbreviation',
            field=models.CharField(help_text='An abbreviation for the party name.', max_length=3, unique=True),
        ),
    ]
