# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0020_auto_20161018_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatescrapedelection',
            name='year',
        ),
        migrations.RemoveField(
            model_name='propositionscrapedelection',
            name='date',
        ),
        migrations.RemoveField(
            model_name='propositionscrapedelection',
            name='election_id',
        ),
        migrations.RemoveField(
            model_name='propositionscrapedelection',
            name='sort_index',
        ),
        migrations.RemoveField(
            model_name='scrapedproposition',
            name='description',
        ),
        migrations.AlterField(
            model_name='candidatescrapedelection',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propositionscrapedelection',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
