# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0022_ballotmeasurecontestidentifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ('name',), 'verbose_name_plural': 'parties'},
        ),
    ]
