# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0023_auto_20161115_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(blank=True, choices=[('P', 'Primary'), ('G', 'General'), ('S', 'Special'), ('R', 'Recall')], help_text='Type of election', max_length=1, verbose_name='election type')),
                ('year', models.CharField(blank=True, help_text='Election year', max_length=4, verbose_name='election year')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('proposition_id', models.IntegerField(help_text='Proposition unique id cast as an integer.', primary_key=True, serialize=False, unique=True, verbose_name='proposition ID')),
                ('name', models.CharField(blank=True, help_text='Name of the proposition', max_length=500, verbose_name='name')),
                ('election', models.ForeignKey(help_text='Foreign key referring to the election in which thisproposition was on the ballot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election', to='calaccess_processed.Election')),
            ],
        ),
        migrations.CreateModel(
            name='PropositionCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_id', models.IntegerField(help_text='Committee id', verbose_name='committee ID')),
                ('name', models.CharField(blank=True, help_text='Name of the proposition', max_length=500, verbose_name='name')),
                ('proposition', models.ForeignKey(db_constraint=False, help_text='Foreign key referring to the proposition that this committee supports or opposes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to='calaccess_processed.Proposition')),
            ],
        ),
    ]
