# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0023_auto_20170206_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotmeasurecontest',
            name='ballot_measure_type',
            field=models.CharField(blank=True, choices=[('ballot-measure', 'Ballot Measure'), ('initiative', 'Initiative'), ('referendum', 'Referendum'), ('other', 'Other')], help_text='Enumerated among:\n\t* ballot-measure: A catch-all for generic types of non-candidate-based contests.\n\t* initiative: These are usually citizen-driven measures to be placed on the ballot. These could include both statutory changes and constitutional amendments.\n\t* referendum: These could include measures to repeal existing acts of legislation, legislative referrals, and legislatively-referred state constitutional amendments.\n\t* other: Anything that does not fall into the above categories.', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='classification',
            field=models.CharField(choices=[('committee-meeting', 'Committee Meeting'), ('election', 'Election'), ('hearing', 'Hearing')], help_text='Classification of the event.', max_length=300),
        ),
    ]
