# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:21
from __future__ import unicode_literals

import calaccess_processed.models.opencivicdata.base
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0025_auto_20170206_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotSelectionBase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time that this object was created at in the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time that this object was last updated in the system.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Common to all Open Civic Data types, the value is a key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('id', calaccess_processed.models.opencivicdata.base.OCDIDField(help_text='Open Civic Data-style id in the format ``ocd-ballotselection/{{uuid}}``.', ocd_type='ballotselection', serialize=False, validators=[django.core.validators.RegexValidator(flags=32, message='ID must match ^ocd-ballotselection/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$', regex='^ocd-ballotselection/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ballotmeasureselection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ballotmeasureselection',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='ballotmeasureselection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ballotmeasureselection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='candidateselection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidateselection',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='candidateselection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='candidateselection',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ballotmeasureselection',
            name='ballotselectionbase_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calaccess_processed.BallotSelectionBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='ballotselectionbase_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calaccess_processed.BallotSelectionBase'),
            preserve_default=False,
        ),
    ]
