# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0025_auto_20161116_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='proposition_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='propositioncommittee',
            name='committee_id',
        ),
        migrations.AlterField(
            model_name='propositioncommittee',
            name='id',
            field=models.IntegerField(help_text='Committee id', primary_key=True, serialize=False, verbose_name='committee ID'),
        ),
    ]
