# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0026_auto_20170206_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidacy',
            old_name='candidate_selection',
            new_name='ballot_selection',
        ),
        migrations.AlterField(
            model_name='ballotmeasureselection',
            name='contest',
            field=models.ForeignKey(help_text='References the ``BallotMeasureContest`` in which the selection is an option.', on_delete=django.db.models.deletion.CASCADE, related_name='ballot_selections', to='calaccess_processed.BallotMeasureContest'),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='contest',
            field=models.ForeignKey(help_text='References the ``CandidateContest`` in which the selection is an option.', on_delete=django.db.models.deletion.CASCADE, related_name='ballot_selections', to='calaccess_processed.CandidateContest'),
        ),
    ]
