# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0027_auto_20170206_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestbase',
            name='division',
            field=models.ForeignKey(help_text='Reference to the OCD ``Division`` that defines the geographical scope of the contest, e.g., a specific Congressional or State Senate district.', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='calaccess_processed.Division'),
        ),
        migrations.AlterField(
            model_name='contestbase',
            name='election',
            field=models.ForeignKey(help_text='Reference to the OCD ``Election`` in which the contest is decided.', on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='calaccess_processed.Election'),
        ),
    ]
