# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0027_auto_20161116_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositioncommittee',
            name='position',
            field=models.CharField(choices=[('S', 'Support'), ('O', 'Oppose')], default='S', help_text='Whether the committee supports or opposes the proposition', max_length=1),
            preserve_default=False,
        ),
    ]
