# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0028_propositioncommittee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propositioncommittee',
            name='committee_filer_id',
        ),
        migrations.AlterField(
            model_name='propositioncommittee',
            name='id',
            field=models.IntegerField(help_text='Committee unique id cast as an integer.', primary_key=True, serialize=False, unique=True, verbose_name='committee ID'),
        ),
    ]
