# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0028_auto_20170207_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotSelectionSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=2000)),
                ('ballot_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='calaccess_processed.BallotSelectionBase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidacySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=2000)),
                ('candidacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='calaccess_processed.Candidacy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContestSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=2000)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='calaccess_processed.ContestBase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=2000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='calaccess_processed.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=2000)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='calaccess_processed.Party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
