# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0029_ballotselectionsource_candidacysource_contestsource_eventsource_partysource'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatescrapedelection',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='propositionscrapedelection',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcandidate',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcandidatecommittee',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scrapedproposition',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scrapedpropositioncommittee',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
