# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:24
from __future__ import unicode_literals
from calaccess_processed.models.opencivicdata.elections.contest import CandidateContest

from django.db import migrations, models

def forwards(apps, schema_editor):
    CandidateContest.objects.update(number_elected='1')

class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0030_auto_20170207_2031'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.AlterField(
            model_name='candidatecontest',
            name='number_elected',
            field=models.IntegerField(default=1, help_text="Number of candidates that are elected in the contest, i.e. 'N' of N-of-M."),
        ),
    ]
