# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0030_auto_20161122_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositioncommittee',
            name='opposes',
            field=models.ManyToManyField(related_name='opposing_committees', to='calaccess_processed.Proposition'),
        ),
        migrations.AddField(
            model_name='propositioncommittee',
            name='supports',
            field=models.ManyToManyField(related_name='supporting_committees', to='calaccess_processed.Proposition'),
        ),
    ]
