# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0031_auto_20170208_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballotmeasurecontest',
            options={'ordering': ('election', 'name')},
        ),
        migrations.AlterModelOptions(
            name='candidacy',
            options={'ordering': ('ballot_selection', 'post', 'person'), 'verbose_name_plural': 'candidacies'},
        ),
        migrations.AlterModelOptions(
            name='candidatecontest',
            options={'ordering': ('election', 'name')},
        ),
        migrations.AlterModelOptions(
            name='candidateselection',
            options={'ordering': ('contest',)},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ('-start_time',)},
        ),
    ]
