# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0034_auto_20170218_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileridvalue',
            options={'verbose_name': 'RESEARCH: Filer ID value'},
        ),
        migrations.AlterModelOptions(
            name='filingidvalue',
            options={'verbose_name': 'RESEARCH: Filing ID value'},
        ),
    ]
