# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0035_auto_20170218_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule497part1item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schedule497part2item',
            options={},
        ),
    ]
