# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0036_auto_20170219_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form460filing',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) filing'},
        ),
        migrations.AlterModelOptions(
            name='form460filingversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) filing version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleaitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule A item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleaitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule A item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleb1item',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule B item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleb1itemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule B item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleb2item',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule B2 item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleb2itemold',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule B2 old item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleb2itemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule B2 item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleb2itemversionold',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule B2 old item version'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulecitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule C item'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulecitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule C item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleditem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule D item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleditemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule D item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleeitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule E item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleeitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule E item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleesubitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule E subitem'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleesubitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule E subitem version'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulefitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule F item'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulefitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule F item version'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulegitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule G item'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulegitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule G item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleh2itemold',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule H2 old item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleh2itemversionold',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule H2 old item version'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulehitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule H item'},
        ),
        migrations.AlterModelOptions(
            name='form460schedulehitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule H item version'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleiitem',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule I item'},
        ),
        migrations.AlterModelOptions(
            name='form460scheduleiitemversion',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule I item version'},
        ),
        migrations.AlterModelOptions(
            name='form501filing',
            options={'verbose_name': 'Form 501 (Candidate Intention) filing'},
        ),
        migrations.AlterModelOptions(
            name='form501filingversion',
            options={'verbose_name': 'Form 501 (Candidate Intention) filing version'},
        ),
        migrations.AlterModelOptions(
            name='schedule497filing',
            options={'verbose_name': 'Form 497 (Late Contribution) filing'},
        ),
        migrations.AlterModelOptions(
            name='schedule497filingversion',
            options={'verbose_name': 'Form 497 (Late Contribution) filing version'},
        ),
        migrations.AlterModelOptions(
            name='schedule497part1item',
            options={'verbose_name': 'Form 497 (Late Contribution) Part 1 item'},
        ),
        migrations.AlterModelOptions(
            name='schedule497part1itemversion',
            options={'verbose_name': 'Form 497 (Late Contribution) Part 1 item version'},
        ),
        migrations.AlterModelOptions(
            name='schedule497part2item',
            options={'verbose_name': 'Form 497 (Late Contribution) Part 2 item'},
        ),
        migrations.AlterModelOptions(
            name='schedule497part2itemversion',
            options={'verbose_name': 'Form 497 (Late Contribution) Part 2 item version'},
        ),
    ]
