# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form460ScheduleASummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemized_contributions', models.IntegerField(help_text='Amount received this period - contributions of $100 or more. (Include all Schedule A subtotals.)', null=True, verbose_name='itemized contributions')),
                ('unitemized_contributions', models.IntegerField(help_text='Amount received this period - unitemized contributions of less than $100', null=True, verbose_name='unitemized contributions')),
                ('total_contributions', models.IntegerField(help_text='Total monetary contributions received this period. (Add Lines 1 and 2. Enter here and on summary Page, Column A, Line 1.)', null=True, verbose_name='total contributions')),
                ('filing', models.ForeignKey(help_text='Foreign key referring to the Form 460 on which the summary was reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_a_summaries', to='calaccess_processed.Form460Filing')),
            ],
            options={
                'verbose_name': 'Form 460 (Campaign Disclosure) Schedule A summary',
            },
        ),
        migrations.CreateModel(
            name='Form460ScheduleASummaryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemized_contributions', models.IntegerField(help_text='Amount received this period - contributions of $100 or more. (Include all Schedule A subtotals.)', null=True, verbose_name='itemized contributions')),
                ('unitemized_contributions', models.IntegerField(help_text='Amount received this period - unitemized contributions of less than $100', null=True, verbose_name='unitemized contributions')),
                ('total_contributions', models.IntegerField(help_text='Total monetary contributions received this period. (Add Lines 1 and 2. Enter here and on summary Page, Column A, Line 1.)', null=True, verbose_name='total contributions')),
                ('filing_version', models.ForeignKey(help_text='Foreign key referring to the version of the Form 460 that includes the summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_a_summaries', to='calaccess_processed.Form460FilingVersion')),
            ],
            options={
                'verbose_name': 'Form 460 (Campaign Disclosure) Schedule A summary version',
            },
        ),
    ]
