# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0039_form460scheduleasummary_form460scheduleasummaryversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form460scheduleasummary',
            options={'verbose_name': 'Form 460 (Campaign Disclosure) Schedule A summary', 'verbose_name_plural': 'Form 460 (Campaign Disclosure) Schedule A summaries'},
        ),
        migrations.AlterField(
            model_name='form460scheduleasummary',
            name='itemized_contributions',
            field=models.FloatField(help_text='Amount received this period - contributions of $100 or more. (Include all Schedule A subtotals.)', null=True, verbose_name='itemized contributions'),
        ),
        migrations.AlterField(
            model_name='form460scheduleasummary',
            name='total_contributions',
            field=models.FloatField(help_text='Total monetary contributions received this period. (Add Lines 1 and 2. Enter here and on summary Page, Column A, Line 1.)', null=True, verbose_name='total contributions'),
        ),
        migrations.AlterField(
            model_name='form460scheduleasummary',
            name='unitemized_contributions',
            field=models.FloatField(help_text='Amount received this period - unitemized contributions of less than $100', null=True, verbose_name='unitemized contributions'),
        ),
        migrations.AlterField(
            model_name='form460scheduleasummaryversion',
            name='itemized_contributions',
            field=models.FloatField(help_text='Amount received this period - contributions of $100 or more. (Include all Schedule A subtotals.)', null=True, verbose_name='itemized contributions'),
        ),
        migrations.AlterField(
            model_name='form460scheduleasummaryversion',
            name='total_contributions',
            field=models.FloatField(help_text='Total monetary contributions received this period. (Add Lines 1 and 2. Enter here and on summary Page, Column A, Line 1.)', null=True, verbose_name='total contributions'),
        ),
        migrations.AlterField(
            model_name='form460scheduleasummaryversion',
            name='unitemized_contributions',
            field=models.FloatField(help_text='Amount received this period - unitemized contributions of less than $100', null=True, verbose_name='unitemized contributions'),
        ),
    ]
