# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0040_auto_20170314_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form460ScheduleCSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemized_contributions', models.FloatField(help_text='Amount received this period - itemized nonmonetary contributions. (Include all Schedule C subtotals)', null=True, verbose_name='itemized contributions')),
                ('unitemized_contributions', models.FloatField(help_text='Amount received this period - unitemized nonmonetary contributions of less than $100', null=True, verbose_name='unitemized contributions')),
                ('total_contributions', models.FloatField(help_text='Total nonmonetary contributions received this period. (Add Lines 1 and 2. Enter here and on the Summary Page, Column A, Lines 4 and 10.)', null=True, verbose_name='total contributions')),
                ('filing', models.ForeignKey(help_text='Foreign key referring to the Form 460 on which the summary was reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_c_summaries', to='calaccess_processed.Form460Filing')),
            ],
            options={
                'verbose_name': 'Form 460 (Campaign Disclosure) Schedule A summary',
                'verbose_name_plural': 'Form 460 (Campaign Disclosure) Schedule A summaries',
            },
        ),
        migrations.CreateModel(
            name='Form460ScheduleCSummaryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemized_contributions', models.FloatField(help_text='Amount received this period - itemized nonmonetary contributions. (Include all Schedule C subtotals)', null=True, verbose_name='itemized contributions')),
                ('unitemized_contributions', models.FloatField(help_text='Amount received this period - unitemized nonmonetary contributions of less than $100', null=True, verbose_name='unitemized contributions')),
                ('total_contributions', models.FloatField(help_text='Total nonmonetary contributions received this period. (Add Lines 1 and 2. Enter here and on the Summary Page, Column A, Lines 4 and 10.)', null=True, verbose_name='total contributions')),
                ('filing_version', models.ForeignKey(help_text='Foreign key referring to the version of the Form 460 that includes the summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_c_summaries', to='calaccess_processed.Form460FilingVersion')),
            ],
            options={
                'verbose_name': 'Form 460 (Campaign Disclosure) Schedule A summary version',
            },
        ),
    ]
