# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0042_auto_20170324_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddataversion',
            name='raw_version',
            field=models.OneToOneField(help_text='Foreign key referencing the raw data version processed', on_delete=django.db.models.deletion.CASCADE, related_name='processed_version', to='calaccess_raw.RawDataVersion', verbose_name='raw data version'),
        ),
    ]
