# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0043_auto_20170524_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form460ScheduleESummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemized_expenditures', models.FloatField(help_text='Payments made this period of $100 or more. (Include all Schedule E subtotals.)', null=True, verbose_name='itemized expenditures')),
                ('unitemized_expenditures', models.FloatField(help_text='Unitemized payments made this period of under $100.', null=True, verbose_name='unitemized expenditures')),
                ('interest_paid', models.FloatField(help_text='Total interest paid this period on loans. (Enter amount from Schedule B, Part 1, Column (e).)', null=True, verbose_name='interest paid')),
                ('total_expenditures', models.FloatField(help_text='Total payments made this period. (Add lines 1, 2, and 3. Enter here and on the Summary Page, Column A, Line 6.) ', null=True, verbose_name='total expenditures')),
                ('filing', models.ForeignKey(help_text='Foreign key referring to the Form 460 on which the summary was reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_e_summaries', to='calaccess_processed.Form460Filing')),
            ],
            options={
                'verbose_name': 'Form 460 (Campaign Disclosure) Schedule E summary',
                'verbose_name_plural': 'Form 460 (Campaign Disclosure) Schedule E summaries',
            },
        ),
        migrations.CreateModel(
            name='Form460ScheduleESummaryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemized_expenditures', models.FloatField(help_text='Payments made this period of $100 or more. (Include all Schedule E subtotals.)', null=True, verbose_name='itemized expenditures')),
                ('unitemized_expenditures', models.FloatField(help_text='Unitemized payments made this period of under $100.', null=True, verbose_name='unitemized expenditures')),
                ('interest_paid', models.FloatField(help_text='Total interest paid this period on loans. (Enter amount from Schedule B, Part 1, Column (e).)', null=True, verbose_name='interest paid')),
                ('total_expenditures', models.FloatField(help_text='Total payments made this period. (Add lines 1, 2, and 3. Enter here and on the Summary Page, Column A, Line 6.) ', null=True, verbose_name='total expenditures')),
                ('filing_version', models.ForeignKey(help_text='Foreign key referring to the version of the Form 460 that includes the summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_e_summaries', to='calaccess_processed.Form460FilingVersion')),
            ],
            options={
                'verbose_name': 'Form 460 (Campaign Disclosure) Schedule E summary version',
            },
        ),
    ]
