# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_processed', '0044_form460scheduleesummary_form460scheduleesummaryversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncumbentScrapedElection',
        ),
        migrations.RemoveField(
            model_name='scrapedcandidate',
            name='election',
        ),
        migrations.DeleteModel(
            name='ScrapedCandidateCommittee',
        ),
        migrations.DeleteModel(
            name='ScrapedIncumbent',
        ),
        migrations.RemoveField(
            model_name='scrapedproposition',
            name='election',
        ),
        migrations.RemoveField(
            model_name='scrapedpropositioncommittee',
            name='proposition',
        ),
        migrations.DeleteModel(
            name='CandidateScrapedElection',
        ),
        migrations.DeleteModel(
            name='PropositionScrapedElection',
        ),
        migrations.DeleteModel(
            name='ScrapedCandidate',
        ),
        migrations.DeleteModel(
            name='ScrapedProposition',
        ),
        migrations.DeleteModel(
            name='ScrapedPropositionCommittee',
        ),
    ]
