# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 02:34
from __future__ import unicode_literals

import calaccess_processed.models.proxies.calaccess_scraped.candidates
import calaccess_processed.models.proxies.calaccess_scraped.electionsbase
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_scraped', '0002_auto_20170628_1500'),
        ('elections', '0001_initial'),
        ('calaccess_raw', '0015_auto_20170729_0215'),
        ('core', '0002_post_maximum_memberships'),
        ('calaccess_processed', '0045_auto_20170626_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDCandidacyProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('elections.candidacy',),
        ),
        migrations.CreateModel(
            name='OCDDivisionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.division',),
        ),
        migrations.CreateModel(
            name='OCDElectionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('elections.election',),
        ),
        migrations.CreateModel(
            name='OCDOrganizationProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='OCDPartyProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='OCDPersonProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='OCDPostProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.post',),
        ),
        migrations.CreateModel(
            name='OCDRunoffProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('elections.candidatecontest',),
        ),
        migrations.CreateModel(
            name='RawFilerToFilerTypeCdProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('calaccess_raw.filertofilertypecd',),
        ),
        migrations.CreateModel(
            name='ScrapedCandidateElectionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(calaccess_processed.models.proxies.calaccess_scraped.electionsbase.ElectionProxyMixin, 'calaccess_scraped.candidateelection'),
        ),
        migrations.CreateModel(
            name='ScrapedCandidateProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('calaccess_scraped.candidate', calaccess_processed.models.proxies.calaccess_scraped.candidates.ScrapedNameMixin),
        ),
        migrations.CreateModel(
            name='ScrapedIncumbentElectionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(calaccess_processed.models.proxies.calaccess_scraped.electionsbase.ElectionProxyMixin, 'calaccess_scraped.incumbentelection'),
        ),
        migrations.CreateModel(
            name='ScrapedIncumbentProxy',
            fields=[
            ],
            options={
                'ordering': ['-session'],
                'proxy': True,
                'indexes': [],
            },
            bases=('calaccess_scraped.incumbent', calaccess_processed.models.proxies.calaccess_scraped.candidates.ScrapedNameMixin),
        ),
        migrations.CreateModel(
            name='ScrapedPropositionElectionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(calaccess_processed.models.proxies.calaccess_scraped.electionsbase.ElectionProxyMixin, 'calaccess_scraped.propositionelection'),
        ),
        migrations.CreateModel(
            name='ScrapedPropositionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('calaccess_scraped.proposition',),
        ),
    ]
